[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Identy"
authors = [{name = "GSE", email = "area.comercial@gse.com.co"}]
dynamic = ["version", "description"]
